version: '3'

services:
  app:
    build:
      context: .
      args: 
        - IMAGE_VERSION=3.7.0-alpine3.8
    image: takacsnark/flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000

  redis:
    image: redis:4.0.11-alpine